### ISSUE TITLE
Onde posso encontrar a documentação?

### ISSUE THREAD

**Issue by gabListon** [scieloorg/articlemetaapi#15]
Estou procurando por uma documentação, mas não encontrei nada além do readme deste repositório.

Mais especificamente, gostaria de saber se a API é capaz de realizar busca de artigos por palavras-chave, ou funciona apenas com coleções, como no exemplo do readme?

**Comment by robertatakenaka** [comment]
@gabListon não há nenhuma API disponível para busca
